[package]
name = "meshy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluer = { version = "0.15.0", features = ["bluetoothd"] }
env_logger = "0.9.0"
tokio = "1.18.1"
